CREATE TABLE IF NOT EXISTS vehicle_damage.opensource_image_catalog (
    image_id VARCHAR(64) NOT NULL,
    source_dataset VARCHAR(64),
    image_s3_key VARCHAR(1024),
    processed_s3_key VARCHAR(1024),
    is_damaged BOOLEAN,
    damage_class VARCHAR(128),
    damage_severity VARCHAR(32),
    damage_zones SUPER,
    has_segmentation_mask BOOLEAN,
    mask_s3_key VARCHAR(1024),
    make VARCHAR(128),
    model VARCHAR(256),
    year VARCHAR(16),
    source_confidence DOUBLE PRECISION,
    normalized_at TIMESTAMP,
    resolution_w INTEGER,
    resolution_h INTEGER,
    blur_score DOUBLE PRECISION,
    brightness_mean DOUBLE PRECISION,
    phash_fingerprint VARCHAR(128),
    status VARCHAR(32),
    ingested_at TIMESTAMP DEFAULT GETDATE()
);
